### ISSUE TITLE
Meta-desc/title/key missing

### ISSUE THREAD

**Issue by Goran-n** [oleksandr-torosh/yona-cms#44]
For the Meta-Description , Title and Keyword the fields are missing and cannot be updated. I have tried cloning the master source on 3 computers and still the meta tags cannot be updated. They always output as null.

**Comment by Goran-n** [comment]
Fixed by changing the form names from "meta_title" to "metaTitle" - this is a phalcon problem

**Comment by zikezhang** [comment]
Hi @Goran-n 

>  Fixed by changing the form names from "meta_title" to "metaTitle" - this is a phalcon problem

 my Publication\Form\TypeForm 

`$this->add((new Text('headTitle'))->setLabel('Head Title'));`


/Publication/views/type/edit.volt

`{{ form.renderDecorated('headTitle') }}`

/Publication/Model/Type.php

     `/**
     * @param mixed $head_title
     */
    public function setHead_title($head_title)
    {
        $this->setMetaVariable('headTitle', $head_title);
    }
      /**
     * @return mixed
     */
     public function getHead_title()
    {
        return $this->getMetaVariable('headTitle');
    }`

so, what I missed ?

Thanks !

**Comment by zikezhang** [comment]
Maybe "meta_title" has conflict with phalcon.

but I think "seo_text" should be update-able.

And may I know how to figure it out ?

Thanks !

**Comment by Goran-n** [comment]
For me none of the fields were up datable. Below is my new model file:

`<?php
namespace Publication\Model;
use Application\Mvc\Model\Model;
use Phalcon\Mvc\Model\Validator\Uniqueness;
use Phalcon\Mvc\Model\Validator\PresenceOf;
use Application\Localization\Transliterator;
class Publication extends Model
{
    public function getSource()
    {
        return "publication";
    }
    protected $translateModel = 'Publication\Model\Translate\PublicationTranslate'; // translate
    public function initialize()
    {
        $this->hasMany('id', $this->translateModel, 'foreign_id'); // translate
        $this->belongsTo('type_id', 'Publication\Model\Type', 'id', [
            'alias' => 'type'
        ]);
    }
    private $id;
    private $type_id;
    private $slug;
    private $created_at;
    private $updated_at;
    private $date;
    private $preview_src;
    private $preview_inner;
    protected $title;
    protected $text;
    protected $meta_title;
    protected $meta_description;
    protected $meta_keywords;
    public function beforeCreate()
    {
        $this->created_at = date("Y-m-d H:i:s");
    }
    public function beforeUpdate()
    {
        $this->updated_at = date("Y-m-d H:i:s");
    }
    public function afterUpdate()
    {
        parent::afterUpdate();
        $cache = $this->getDi()->get('cache');
        $cache->delete(self::cacheSlugKey($this->getSlug()));
    }
    public function validation()
    {
        $this->validate(new Uniqueness(
            [
                "field"   => "slug",
                "message" => "Страница с такой транслитерацией = '" . $this->slug . "' уже существует"
            ]
        ));
        return $this->validationHasFailed() != true;
    }
    public function afterValidation()
    {
        if (!$this->date) {
            $this->date = date("Y-m-d H:i:s");
        }
    }
    public function updateFields($data)
    {
        if (!$this->getSlug()) {
            $this->setSlug(Transliterator::slugify($data['title']));
        }
        if (!$this->getMetaTitle()) {
            $this->setMetaTitle($data['title']);
        }
        $this->setPreviewInner(isset($data['preview_inner']) ? 1 : 0);
    }
    public static function findCachedBySlug($slug)
    {
        $publication = self::findFirst(["slug = '$slug'",
            'cache' => [
                'key'      => self::cacheSlugKey($slug),
                'lifetime' => 60]
        ]);
        return $publication;
    }
    public static function cacheSlugKey($slug)
    {
        $key = HOST_HASH . md5('Publication\Model\Publication; slug = ' . $slug);
        return $key;
    }
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
    }
    public function getCreatedAt()
    {
        return $this->created_at;
    }
    public function setId($id)
    {
        $this->id = $id;
    }
    public function getId()
    {
        return $this->id;
    }
    public function setMetaDescription($meta_description)
    {
        $this->setMLVariable('meta_description', $meta_description);
    }
    public function getMetaDescription()
    {
        return $this->getMLVariable('meta_description');
    }
    public function setMetaKeywords($meta_keywords)
    {
        $this->setMLVariable('meta_keywords', $meta_keywords);
    }
    public function getMetaKeywords()
    {
        return $this->getMLVariable('meta_keywords');
    }
    public function setMetaTitle($meta_title)
    {
        $this->setMLVariable('meta_title', $meta_title);
    }
    public function getMetaTitle()
    {
        return $this->getMLVariable('meta_title');
    }
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }
    public function getSlug()
    {
        return $this->slug;
    }
    public function setText($text)
    {
        $this->setMLVariable('text', $text);
    }
    public function getText()
    {
        return $this->getMLVariable('text');
    }
    public function setTitle($title)
    {
        $this->setMLVariable('title', $title);
    }
    public function getTitle()
    {
        return $this->getMLVariable('title');
    }
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;
    }
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }
    public function setDate($date)
    {
        $this->date = $date;
    }
    public function getDate($format = 'Y-m-d H:i:s')
    {
        if ($format) {
            if ($this->date) {
                return date($format, strtotime($this->date));
            }
        } else {
            return $this->date;
        }
    }
    public function setType_id($type_id)
    {
        $this->type_id = $type_id;
    }
    public function getType_id()
    {
        return $this->type_id;
    }
    public function getTypeTitle()
    {
        if ($this->type_id) {
            $types = Type::cachedListArray(['key' => 'id']);
            if (array_key_exists($this->type_id, $types)) {
                return $types[$this->type_id];
            }
        }
    }
    public function getTypeSlug()
    {
        if ($this->type_id) {
            $types = Type::cachedListArray(['key' => 'id', 'value' => 'slug']);
            if (array_key_exists($this->type_id, $types)) {
                return $types[$this->type_id];
            }
        }
    }
    public function setPreviewInner($preview_inner)
    {
        $this->preview_inner = $preview_inner;
    }
    public function getPreviewInner()
    {
        return $this->preview_inner;
    }
    public function getPreviewSrc()
    {
        return $this->preview_src;
    }
    public function setPreviewSrc($preview_src)
    {
        $this->preview_src = $preview_src;
    }
}`

**Comment by zikezhang** [comment]
got it , thanks !

**Comment by oleksandr-torosh** [comment]
@zikezhang @Goran-n Hey guys. It would be good if someone create Pull Request with fixing. Thanks.
BTW, DO NOT USE dev branch for this :)

**Comment by oleksandr-torosh** [comment]
Issue fixed. Available on master branch
