### ISSUE TITLE
Can't update data in *_translate table.

### ISSUE THREAD

**Issue by zikezhang** [oleksandr-torosh/yona-cms#50]
pls refer to my screenshot
 
![can_not_update_meta](https://cloud.githubusercontent.com/assets/5647317/14368010/12577990-fce9-11e5-99e3-f3cba14e5330.png)

**Comment by zikezhang** [comment]
I want update meta-title for one of the publication. After click save button and found there is no update.
I can update it in http://demo.yonacms.com/admin.

But after install a fresh code from Github. some of data is un-updateable.

**Comment by oleksandr-torosh** [comment]
https://github.com/oleksandr-torosh/yona-cms/issues/44

**Comment by zikezhang** [comment]
>  Fixed by changing the form names from "meta_title" to "metaTitle" - this is a phalcon problem

 my Publication\Form\TypeForm 

`$this->add((new Text('headTitle'))->setLabel('Head Title'));`


/Publication/views/type/edit.volt

`{{ form.renderDecorated('headTitle') }}`

/Publication/Model/Type.php

     `/**
     * @param mixed $head_title
     */
    public function setHead_title($head_title)
    {
        $this->setMetaVariable('headTitle', $head_title);
    }
      /**
     * @return mixed
     */
     public function getHead_title()
    {
        return $this->getMetaVariable('headTitle');
    }`

so, what I missed ?

Thanks !

**Comment by zikezhang** [comment]
Ok,

should be 

`getMetaKeywords()`

But not 

`getMeta_keywords`

**Comment by Goran-n** [comment]
https://github.com/oleksandr-torosh/yona-cms/issues/44

**Comment by oleksandr-torosh** [comment]
Issue fixed. Available on master branch
