### ISSUE TITLE
Need fix in JS

### ISSUE THREAD

**Issue by phpclub** [oleksandr-torosh/yona-cms#51]
If you have download link to file - download not work.
  self.click = function (e) {

   ** 	if (this.target) {
    		    return true;
    	}**
        if (!self.History.enabled) {
            console.log('history disabled');
            return true;
        }

https://github.com/oleksandr-torosh/yona-cms/blob/master/public/static/js/ajax.js

**Comment by oleksandr-torosh** [comment]
https://github.com/oleksandr-torosh/yona-cms/blob/master/public/static/js/ajax.js#L19

You can add class attribute to link
`class="noajax"`

Also, you can disable AJAX pages transitions:
https://github.com/oleksandr-torosh/yona-cms/blob/master/app/config/global.php#L17
