### ISSUE TITLE
Any plan to support phalcon 2.1

### ISSUE THREAD

**Issue by Geeknux** [oleksandr-torosh/yona-cms#52]
Hi, i wonder, is there any plan to support phalcon 2.1 in near future?

**Comment by oleksandr-torosh** [comment]
Sure :) It will support 2.1

**Comment by benrogmans** [comment]
Just installed Phalcon for the first time :) Yona seems to be the most attractive CMS to go for. Could you shed some light on the planning for 2.1 support?

**Comment by benrogmans** [comment]
Does this mean 2.1 will not be supported?

**Comment by zikezhang** [comment]
Yes, is there a version for phalcon 2.1 and PHP7 ?

**Comment by oleksandr-torosh** [comment]
For now - no any version for Phalcon 2.1 and PHP7 since they are not stable yet.

**Comment by oleksandr-torosh** [comment]
Docker image with Phalcon 3.0 support https://github.com/oleksandr-torosh/yona-cms/tree/docker
