### ISSUE TITLE
your demo page is hacked, can we trust?

### ISSUE THREAD

**Issue by Geeknux** [oleksandr-torosh/yona-cms#54]
Hi, i'm sure you noticed that you're demo page is hacked, do you realize what's wrong? is this yona fault or phalcon? or maybe server itself.

is this production ready or not?

**Comment by oleksandr-torosh** [comment]
Fixed.
Demo places on simple shared hosting which was hacked. 
3rd-party reason of hacking which not depends on Phalcon or YonaCMS
