### ISSUE TITLE
Demo, Docs & Dev branch removed?

### ISSUE THREAD

**Issue by tmikaeld** [oleksandr-torosh/yona-cms#59]
Is this for the upcoming 0.5 version or is the project shutting down?

**Comment by sergeyklay** [comment]
Ya, also there is broken links in README.md:

![61ef637910614ced88c73dc24d413201](https://cloud.githubusercontent.com/assets/1256298/18270192/76a001e8-7434-11e6-9327-65f5e37756dc.png)

**Comment by jasongutt** [comment]
The demo on the Project website is also broken [http://demo.yonacms.com/](http://demo.yonacms.com/)

**Comment by oleksandr-torosh** [comment]
Started new branch with Phalcon 3.x support and Docker image implementation
https://github.com/oleksandr-torosh/yona-cms/tree/docker

**Comment by tmikaeld** [comment]
Impressive, thank you. Will try it out tomorrow!
