### ISSUE TITLE
A few docker branch bugs

### ISSUE THREAD

**Issue by tmikaeld** [oleksandr-torosh/yona-cms#61]
This is to make the docker install work:
1. Copying nginx conf from nowhere, should be: `cp /var/www/yona-cms/docker/etc/nginx/conf.d/yona.conf /etc/nginx/conf.d/yona.conf` after git clone and workdir is set to /var/www
2. root path is wrong in yona.conf, is `/varwww/yona-cms/public;` should be `/var/www/yona-cms/public;`
3. php5-mysql is missing `apt-get install php5-mysql`
4. php5-fpm need proper nginx user `usermod -a -G www-data nginx`
5. php5-gd is missing `apt-get install php5-gd`

Also, it seems semantic-ui is missing from default template (should it be?).

And i see this in the source, what is it used for?
`https://api.github.com/repos/oleksandr-torosh/yona-cms?callback=callback`

**Comment by oleksandr-torosh** [comment]
Already fixed many issues and pushed to branch
