### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by webdesign7** [oleksandr-torosh/yona-cms#73]
Hi, 

Your demo  and documentations are not working ?!

Can you check ?
Thanks

**Comment by sergeyklay** [comment]
Refs: https://github.com/oleksandr-torosh/yona-cms/issues/66, https://github.com/oleksandr-torosh/yona-cms/issues/59

**Comment by oleksandr-torosh** [comment]
I will restore it soon

**Comment by oleksandr-torosh** [comment]
http://demo.yonacms.com/
