### ISSUE TITLE
Install on Xampp error

### ISSUE THREAD

**Issue by esoftcard** [oleksandr-torosh/yona-cms#78]
If install yonacms on xampp, htaccess seem not work right. 

Site can't be loaded with css and run localhost/yonacms/admin get error

**Comment by sergeyklay** [comment]
Could you please provide a bit more info? Apache access/error logs, VirtualHost config, PHP logs, etc.

**Comment by esoftcard** [comment]
Every time i access application, I have to run to public in order to load index page. for example: i have yona-cms folder , it's not auto load index page and have to run yona-cms/public to access homepage.

All the link in application link without : "yona-cms/public/" . So it link to : http://localhost/admin for example, instead of  http://localhost/yona-cms/public/admin

**Comment by sergeyklay** [comment]
Try to set up [Url component](https://github.com/oleksandr-torosh/yona-cms/blob/master/app/Bootstrap.php#L47-L50):

https://github.com/oleksandr-torosh/yona-cms/blob/master/app/config/environment/development.php#L4-L5

**Comment by esoftcard** [comment]
it works now

**Comment by sergeyklay** [comment]
@oleksandr-torosh

**Comment by oleksandr-torosh** [comment]
awesome
