### ISSUE TITLE
Fatal error: Call to a member function delete() on null

### ISSUE THREAD

**Issue by vietdien2005** [oleksandr-torosh/yona-cms#82]
I edit Page in Admin CMS and it show this error:

`Fatal error: Call to a member function delete() on null in <my_path>/app/modules/Page/Model/Page.php on line 56`

- It still update in database 
- Its look like something wrong in function delete in Application\Cache\Manager

**Comment by vietdien2005** [comment]
I found solution for this error:

I change function afterUpdate in Page\Model

```
public function afterUpdate()
    {
        $this->getDi()->get('cacheManager')->delete([
            Keys::PAGE,
            $this->slug,
            self::$lang
        ]);
    }
```

And in Publication\Model, too

**Comment by drnasin** [comment]
To be honest I didn't want to push anything 😕 I just did a fix in my branch. Sorry if duplicate...

**Comment by oleksandr-torosh** [comment]
Issue fixed

**Comment by vietdien2005** [comment]
It's okay @drnasin :D 
thank @oleksandr-torosh

**Comment by buingthai** [comment]
i think put that code to Model Base, make property cacheManager can access for all
