### ISSUE TITLE
Phalcon\Mvc\Model::validate() must implement interface Phalcon\ValidationInterface

### ISSUE THREAD

**Issue by Tinywan** [oleksandr-torosh/yona-cms#89]
![phalcon_model](https://cloud.githubusercontent.com/assets/14959876/23249318/a3412e7c-f9de-11e6-9cfc-ee1fabf8fa3d.jpg)

**Comment by oleksandr-torosh** [comment]
@Tinywan Please, upgrade your Phalcon to version 3.0

**Comment by Tinywan** [comment]
@oleksandr-torosh Thanks!
