### ISSUE TITLE
Changing url when session time out (question)

### ISSUE THREAD

**Issue by tankaizhan** [oleksandr-torosh/yona-cms#91]
Hi,

First, great work on yona. Very helpful. I am new to phalcon and yona.  But keen to dig deeper. I have been building a small learning project using yona and so far so good. Works great. The only struggle I have is changing the admin log after session timeout to something else. I am trying to build a two layer user (frontend & backend) site. Can someone kindly hint me which part of the code I should be looking at please? I can't figure it out myself. Many thanks.

**Comment by oleksandr-torosh** [comment]
@tankaizhan you can look here https://github.com/oleksandr-torosh/yona-cms/blob/master/app/plugins/Acl.php#L31
This line handles a scenario when not loginned user (guest) trying to open admin (or any other closed resource) page.
