### ISSUE TITLE
Unexpected rendering

### ISSUE THREAD

**Issue by Iworb** [oleksandr-torosh/yona-cms#94]
Views rendered in wrong order. You could see the result [here](http://ih654714.vds.myihor.ru) (if link will be unavailable, see screenshot below).
Phpinfo's information could be found [here](http://ih654714.vds.myihor.ru/info.php).
It looks really weird, because the same instance on a local server works as expected.
![2017-08-22_173123](https://user-images.githubusercontent.com/6623262/29571119-0c43dcf2-8761-11e7-9553-23693a6b1cd6.png)

**Comment by oleksandr-torosh** [comment]
@Iworb Looks like this is a compatibility problem with Phalcon v3.2.2

**Comment by Iworb** [comment]
Well, I'll check phalcon version on my local server, but it's version above 3 for sure.

**Comment by Iworb** [comment]
I think I've found a problem: trere's no gd/imagick. One of browsers showed me a page with an error about it. I surprised there's no gd library, but now it's all ok with lates version of phalcon.
