### ISSUE TITLE
Broken paths using PHP 7.0.23 and PhalconPHP 3.2.2?

### ISSUE THREAD

**Issue by iamdann** [oleksandr-torosh/yona-cms#95]
After installation going to `http://yona-cms.local/admin` results in a 404 error. Going to `http://yona-cms.local/public/ `returns a page without any assets loaded, these assets can't be found either.

**Comment by oleksandr-torosh** [comment]
@iamdann I think your virtual host configuration (nginx, apache, etc.) isn't correct and has issues.

**Comment by iamdann** [comment]
@oleksandr-torosh Nothing appeared to be wrong with my Apache environment. Setting the base path to `""` solved my problem.

**Comment by oleksandr-torosh** [comment]
@iamdann nice
