### ISSUE TITLE
The YONA Demo Site is throwing an error.

### ISSUE THREAD

**Issue by IWriteThings** [oleksandr-torosh/yona-cms#96]
<img width="1453" alt="screen shot 2017-10-18 at 10 23 53" src="https://user-images.githubusercontent.com/11728899/31732761-7b2a9ec6-b3ee-11e7-854a-9e044f865b5c.png">

The yona demo site is having connection issues and is not loading correctly. Can you please rectify these issues?

**Comment by oleksandr-torosh** [comment]
@IWriteThings fixed
